In [1]:
import tensorflow as tf

In [2]:
images_ds = tf.data.Dataset.list_files('images/*/*', shuffle=False)

for file in images_ds.take(3):
    print(file.numpy())

b'images\\cat\\20 Reasons Why Cats Make the Best Pets....jpg'
b'images\\cat\\7 Foods Your Cat Can_t Eat.jpg'
b'images\\cat\\A cat appears to have caught the....jpg'


In [3]:
class_names = ['cat', 'dog']

In [4]:
image_count = len(images_ds)
image_count

130

In [5]:
train_size = int(image_count*0.8)

train_ds = images_ds.take(train_size)
test_ds = images_ds.skip(train_size)

In [6]:
len(train_ds)

104

In [7]:
len(test_ds)

26

In [11]:
def get_label(file_path):
    import os
    return tf.strings.split(file_path, os.path.sep)[-2]

In [13]:
def process_image(file_path):
    label = get_label(file_path)

    img = tf.io.read_file(file_path)
    img = tf.image.decode_jpeg(img)
    img = tf.image.resize(img, [128,128])

    return img, label

In [ ]:
train_ds = train_ds.map(process_image)
for img, label in train_ds.take(3):
    print('Image: ',img)
;    print('Label: ',label)

Image:  tf.Tensor(
[[[155.       186.       215.      ]
  [156.       187.       216.      ]
  [158.       189.       218.      ]
  ...
  [ 90.99609   84.99609   72.99609 ]
  [ 92.        86.        74.      ]
  [ 93.        87.        75.      ]]

 [[156.01172  187.01172  216.01172 ]
  [157.02344  188.02344  217.02344 ]
  [159.01172  190.01172  219.01172 ]
  ...
  [ 86.98828   82.97656   74.01172 ]
  [ 89.97656   85.96484   77.      ]
  [ 91.        86.98828   78.02344 ]]

 [[159.       190.       219.      ]
  [160.       191.       220.      ]
  [161.01953  192.01953  221.01953 ]
  ...
  [ 80.96094   77.96094   72.96094 ]
  [ 85.        82.        77.      ]
  [ 87.        84.        79.      ]]

 ...

 [[ 91.09766   44.98047   73.17578 ]
  [108.25781   83.16016   86.25781 ]
  [ 36.058594  33.058594  18.058594]
  ...
  [ 51.234375  32.214844  34.195312]
  [ 41.078125  18.078125  26.078125]
  [ 38.941406  24.941406  23.941406]]

 [[141.90625  123.88281  111.91797 ]
  [ 69.91797   58.

In [19]:
def scale(image, label):
    return image/255, label

In [21]:
train_ds = train_ds.map(scale)
for image, label in train_ds.take(5):
    print('****Image: ', image.numpy()[0][0])
    print('****Label: ', label.numpy())

****Image:  [0.60784316 0.7294118  0.84313726]
****Label:  b'cat'
****Image:  [0.6878983  0.69181985 0.672212  ]
****Label:  b'cat'
****Image:  [0.7736826  0.8089767  0.79120713]
****Label:  b'cat'
****Image:  [0.38330558 0.6778809  0.3122568 ]
****Label:  b'cat'
****Image:  [0.03924632 0.07846201 0.04316789]
****Label:  b'cat'
